# Generated by Django 2.0.4 on 2018-05-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photouploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploads',
            name='upload_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
