# Generated by Django 2.0.4 on 2018-05-29 03:24

from django.db import migrations, models
import photouploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('photouploads', '0002_imageuploads_upload_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploads',
            name='upload_path',
        ),
        migrations.AlterField(
            model_name='imageuploads',
            name='document',
            field=models.ImageField(upload_to=photouploads.models.upload),
        ),
    ]
