# Generated by Django 2.0.4 on 2018-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formentry', '0002_auto_20180505_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.TextField(default=' ', null=True, verbose_name='Description(विवरण)'),
        ),
    ]
