# Generated by Django 2.0.4 on 2018-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formentry', '0005_auto_20180514_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalue',
            name='formType',
            field=models.IntegerField(choices=[(1, 'House'), (2, 'Family'), (3, 'Individual')], default=3, verbose_name='Form Target Group'),
        ),
    ]
