# Generated by Django 2.0.4 on 2018-05-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formentry', '0006_formvalue_formtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='sub_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formentry.questions'),
        ),
        migrations.AlterField(
            model_name='headings',
            name='tableName',
            field=models.TextField(verbose_name='Table Name (फारमभित्रको टेबलको हेडिङ्ग)'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answerType',
            field=models.CharField(choices=[('st', 'Simple Text'), ('mc', 'Multiple Choices'), ('sc', 'Select Choices'), ('nv', 'Number Value'), ('yn', 'Yes/No Question')], default='yn', max_length=2),
        ),
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Description(विवरण)'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='unanswering',
            field=models.BooleanField(choices=[(False, 'Yes (खाली छोडे पनि हुने)'), (True, 'No (भर्नै पर्ने)')], default=0, verbose_name='उत्तर दिन पर्ने/नपर्ने'),
        ),
    ]
