# Generated by Django 2.0.4 on 2018-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formentry', '0007_auto_20180517_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
    ]
