# Generated by Django 2.0.4 on 2018-05-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formentry', '0009_auto_20180517_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='headings',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='questions',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description(विवरण)'),
        ),
    ]
