# Generated by Django 2.0.4 on 2018-05-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formentry', '0012_formvalue_jsontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answerType',
            field=models.CharField(choices=[('st', 'Simple Text'), ('mc', 'Multiple Choices'), ('sc', 'Select Choices'), ('nv', 'Number Value'), ('yn', 'Yes/No Question'), ('df', 'मिति Date')], default='yn', max_length=2),
        ),
    ]
