# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_type', models.IntegerField(default=1)),
                ('country', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=40)),
                ('house', models.IntegerField(default=0)),
                ('palika', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('timespent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nagrikta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('reg_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='nagrikta',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='media',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='hobby',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
    ]
