# Generated by Django 2.0.4 on 2018-05-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='myhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.House'),
        ),
    ]
