# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gened', models.CharField(default=b'23', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relntype', models.IntegerField()),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.GeoCode')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='gened',
            field=models.CharField(default=b'23', max_length=60),
        ),
        migrations.AddField(
            model_name='relation',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
        migrations.AddField(
            model_name='family',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
    ]
