# Generated by Django 2.0.4 on 2018-05-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='person2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
            preserve_default=False,
        ),
    ]
