# Generated by Django 2.0.4 on 2018-05-13 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_relation_person2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='पहिलो नाम'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='अन्तिमको नाम'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='विचको नाम'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Family'),
        ),
    ]
