# Generated by Django 2.0.4 on 2018-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180510_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='creator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personal',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
