# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170614_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='person1',
        ),
        migrations.AddField(
            model_name='relation',
            name='family',
            field=models.ForeignKey(default=b'23', on_delete=django.db.models.deletion.CASCADE, to='personal.Family'),
        ),
        migrations.AddField(
            model_name='relation',
            name='person2',
            field=models.ForeignKey(default=b'0010000', on_delete=django.db.models.deletion.CASCADE, related_name='familychild', to='personal.Personal'),
        ),
    ]
