# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20170614_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Family'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal'),
        ),
    ]
