# Generated by Django 2.0.4 on 2018-05-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20180513_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagrikta',
            name='exp_date',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='म्याद सकिने मिति'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, verbose_name='इमेल'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='फोन नं'),
        ),
        migrations.AlterField(
            model_name='nagrikta',
            name='card_type',
            field=models.IntegerField(default=1, verbose_name='कार्डको प्रकार'),
        ),
        migrations.AlterField(
            model_name='nagrikta',
            name='district',
            field=models.CharField(max_length=160, verbose_name='जारी गर्ने जिल्ला'),
        ),
        migrations.AlterField(
            model_name='nagrikta',
            name='number',
            field=models.CharField(max_length=160, verbose_name='कार्ड नं'),
        ),
        migrations.AlterField(
            model_name='nagrikta',
            name='reg_date',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='जारी मिति'),
        ),
    ]
