# Generated by Django 2.0.4 on 2018-05-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180514_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='gender',
            field=models.IntegerField(choices=[(1, 'पुरुष । male'), (2, 'महिला | Female'), (3, 'तेस्रो लिङ्गि'), (4, 'अन्य')], default=1, verbose_name='लिङ्ग | Gender'),
        ),
    ]
