# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20170614_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='gened',
            field=models.CharField(blank=True, default=b'23', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
