# Generated by Django 2.0.4 on 2018-05-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_personal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Creator'),
        ),
    ]
