# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20170615_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fname',
            field=models.CharField(max_length=100, verbose_name=b'First Name'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='gened',
            field=models.CharField(blank=True, default=b'23', max_length=60, null=True, verbose_name=b'Generated Id'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='lname',
            field=models.CharField(max_length=100, verbose_name=b'Last Name'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Middle Name'),
        ),
    ]
