# Generated by Django 2.0.4 on 2018-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20180427_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='gened',
            field=models.CharField(blank=True, default='23', max_length=60, null=True, verbose_name='Generated Id'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
